permissions:
  contents: read
  pages: write

name: PROD - Score Model

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - master
    paths:
      - Pipeline/data/**
      - Pipeline/deploy-score.py
      - .github/workflows/score_model_prod.yml

jobs:
  deploy_ml_scoring_pipeline:
    name: PROD - Deploy the Scoring pipeline to Azure ML
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Repo checkout
      uses: actions/checkout@v3
    - name: Install az CLI
      run: |
        # Install the az CLI and ML extension
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add -n ml -y
        echo "Installed Azure CLI and ML extension"
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    - name: Install and prepare Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Run AML pipeline
      run: |
        cd Pipeline/
        echo "Installing dependencies"
        python -m pip install -r requirements.txt
        echo "Creating config file"
        mkdir .azureml
        echo -e "{ \"subscription_id\": \"${{ secrets.AZURE_SUBSCRIPTION_ID }}\", \"resource_group\": \"fm-resources\", \"workspace_name\": \"fm-resources\" }" > .azureml/config.json
        echo "Run scoring pipeline"
        # Run scoring pipeline
        python deploy-score.py